// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGXyEpIWwwQFVQjNANAJ6KTtROk4nwnoM',
    appId: '1:1080914987712:web:35d22691a42e5e425afb25',
    messagingSenderId: '1080914987712',
    projectId: 'songswipe--tfg',
    authDomain: 'songswipe-tfg-23656.firebaseapp.com',
    storageBucket: 'songswipe--tfg.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5I5NYeoFXAWMTOYJUWmi-xzJXcKnJb2g',
    appId: '1:1080914987712:android:22672416a3a1886e5afb25',
    messagingSenderId: '1080914987712',
    projectId: 'songswipe--tfg',
    storageBucket: 'songswipe--tfg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZDhIbFDSyKvPRnwm1UuZ9ZD3xd-xSN68',
    appId: '1:1080914987712:ios:b1f777659825cb2b5afb25',
    messagingSenderId: '1080914987712',
    projectId: 'songswipe--tfg',
    storageBucket: 'songswipe--tfg.firebasestorage.app',
    iosBundleId: 'com.amarosv.songswipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZDhIbFDSyKvPRnwm1UuZ9ZD3xd-xSN68',
    appId: '1:1080914987712:ios:b1f777659825cb2b5afb25',
    messagingSenderId: '1080914987712',
    projectId: 'songswipe--tfg',
    storageBucket: 'songswipe--tfg.firebasestorage.app',
    iosBundleId: 'com.amarosv.songswipe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGXyEpIWwwQFVQjNANAJ6KTtROk4nwnoM',
    appId: '1:1080914987712:web:0277f7a6d9c96fe55afb25',
    messagingSenderId: '1080914987712',
    projectId: 'songswipe--tfg',
    authDomain: 'songswipe-tfg-23656.firebaseapp.com',
    storageBucket: 'songswipe--tfg.firebasestorage.app',
  );

}