// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtM6C_TMzVIsyUCzj1Iy-Emxr3rSofdV4',
    appId: '1:587484748503:web:c5944669c116f3fe4bae92',
    messagingSenderId: '587484748503',
    projectId: 'songswipe-tfg',
    authDomain: 'songswipe-tfg.firebaseapp.com',
    storageBucket: 'songswipe-tfg.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy5rphozFD8KJDWmNSHW9nWRqDp1v9SuE',
    appId: '1:587484748503:android:e429f715ac467d074bae92',
    messagingSenderId: '587484748503',
    projectId: 'songswipe-tfg',
    storageBucket: 'songswipe-tfg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDR8OXA3kkbiE4cqudM2VAFg9dIwl_NCk',
    appId: '1:587484748503:ios:f5912f28bf2d8ba84bae92',
    messagingSenderId: '587484748503',
    projectId: 'songswipe-tfg',
    storageBucket: 'songswipe-tfg.firebasestorage.app',
    iosBundleId: 'com.amarosv.songswipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDR8OXA3kkbiE4cqudM2VAFg9dIwl_NCk',
    appId: '1:587484748503:ios:f5912f28bf2d8ba84bae92',
    messagingSenderId: '587484748503',
    projectId: 'songswipe-tfg',
    storageBucket: 'songswipe-tfg.firebasestorage.app',
    iosBundleId: 'com.amarosv.songswipe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtM6C_TMzVIsyUCzj1Iy-Emxr3rSofdV4',
    appId: '1:587484748503:web:f5f76fc66641b7d14bae92',
    messagingSenderId: '587484748503',
    projectId: 'songswipe-tfg',
    authDomain: 'songswipe-tfg.firebaseapp.com',
    storageBucket: 'songswipe-tfg.firebasestorage.app',
  );
}
