/// Flutter icons SongSwipe
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SongSwipe
///      fonts:
///       - asset: fonts/SongSwipe.ttf
///
/// 
///
library;
import 'package:flutter/widgets.dart';

class SongSwipe {
  SongSwipe._();

  static const _kFontFam = 'SongSwipe';
  static const String? _kFontPkg = null;

  static const IconData info = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circleNotifications = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData headphones = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData language = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData designServices = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
